src/csvf/urls.py
from django.urls import path
from .views import csv_import_view

app_name = 'csvf'

urlpatterns = [
    path('csv_import', csv_import_view, name='csv_import'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

#import for media files
from django.conf import settings
from django.conf.urls.static import static

#from refshelf import views as refshelf_views
from books import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refshelf/', include('refshelf.urls', namespace='refshelf')),
    path('users/', include('users.urls', namespace='users')),
    path('books/', include('books.urls', namespace='books')),
    path('csvf/', include('csvf.urls', namespace='csvf')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('stmanager/', include('stmanager.urls', namespace='stmanager')),
    path('', book_views.HomeView.as_view(), name='home'),
]

if settings.DEV_MODE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/refshelf/urls.py
from django.urls import path

from refshelf import views as refshelf_views

app_name = 'refshelf'

urlpatterns = [
    path('author/<int:pk>/', refshelf_views.AuthorDetails.as_view(), name='author'),
    path('authors/', refshelf_views.AuthorList.as_view(), name='authors'),
    path('genre/<int:pk>/', refshelf_views.GenreDetails.as_view(), name='genre'),
    path('genres/', refshelf_views.GenreList.as_view(), name='genres'),
    path('publisher/<int:pk>/', refshelf_views.PublisherDetails.as_view(), name='publisher'),
    path('publishers/', refshelf_views.PublisherList.as_view(), name='publishers'),
    path('series/<int:pk>/', refshelf_views.SeriesDetails.as_view(), name='series'),
    path('serieses/', refshelf_views.SeriesList.as_view(), name='serieses'),
]

src/stmanager/urls.py
from django.urls import path

from stmanager import views as manager_views

app_name = 'stmanager'

urlpatterns = [
    path('series_create/', manager_views.SeriesCreate.as_view(), name='series_create'),
    path('series_update/<int:pk>/', manager_views.SeriesUpdate.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', manager_views.SeriesDelete.as_view(), name='series_delete'),
    path('create_res/', manager_views.ViewOrders.as_view(), name='create_res'),
    path('publisher_create/', manager_views.PublisherCreate.as_view(), name='publisher_create'),
    path('publisher_update/<int:pk>/', manager_views.PublisherUpdate.as_view(), name='publisher_update'),
    path('publisher_delete/<int:pk>/', manager_views.PublisherDelete.as_view(), name='publisher_delete'),
    path('genre_create/', manager_views.GenreCreate.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', manager_views.GenreUpdate.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', manager_views.GenreDelete.as_view(), name='genre_delete'),
    path('author_create/', manager_views.AuthorCreate.as_view(), name='author_create'),
    path('author_update/<int:pk>/', manager_views.AuthorUpdate.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', manager_views.AuthorDelete.as_view(), name='author_delete'),
    path('book_create/', manager_views.BookCreate.as_view(), name='book_create'),
    path('book_update/<int:pk>/', manager_views.BookUpdate.as_view(), name='book_update'),
    path('book_delete/<int:pk>/', manager_views.BookDelete.as_view(), name='book_delete'),
    path('cart_ordered/<int:pk>/', manager_views.CartItemsDetail.as_view(), name='cart_ordered'),
    path('change_order_status/<int:pk>/', manager_views.UpdateOrderStatus.as_view(), name='change_order_status'),
]

src/refshelf/models.py
from django.db import models
from django.urls import reverse


class Authors(models.Model):
    first_name = models.CharField(
        verbose_name='Имя автора', 
        max_length=20
        )
    last_name = models.CharField(
        verbose_name='Фамилия автора', 
        max_length=20
        )

    picture = models.ImageField(
        verbose_name='Фото автора',
        upload_to ='authors//%Y/%m/%d/'
    )

    def __str__(self) -> str:
        return f' {self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('refshelf:author', kwargs={'pk': self.pk})    

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

class Genre(models.Model):
    genre_name = models.CharField(
        verbose_name='Название жанра',
        max_length=20
    )
    genre_description = models.TextField(
        verbose_name='Описание жанра',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f'{self.genre_name}'

    def get_absolute_url(self):
        return reverse('refshelf:genre', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

class Publisher(models.Model):
    publisher_name = models.CharField(
        verbose_name='Издательство',
        max_length=20
    )
    publisher_description = models.TextField(
        verbose_name='Информация об издательстве',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f' {self.publisher_name}'

    def get_absolute_url(self):
        return reverse('refshelf:publisher', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'

class BookSeries(models.Model):
    series_name = models.CharField(
        verbose_name='Серия',
        max_length=100
    )
    series_description = models.TextField(
        verbose_name='Описание серии',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f' {self.series_name}'

    def get_absolute_url(self):
        return reverse('refshelf:series', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Серия'
        verbose_name_plural = 'Серии'

src/refshelf/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
)
from . import models 

# Create your views here.

class AuthorDetails(DetailView):
    model = models.Authors

class AuthorList(ListView):
    model = models.Authors

class GenreDetails(DetailView):
    model = models.Genre

class GenreList(ListView):
    model = models.Genre

class PublisherDetails(DetailView):
    model = models.Publisher

class PublisherList(ListView):
    model = models.Publisher

class SeriesDetails(DetailView):
    model = models.BookSeries

class SeriesList(ListView):
    model = models.BookSeries


# def series(request, series_id):
#     series = models.BookSeries.objects.get(pk=series_id)
#     ctx = {
#         'series': series
#     }
#     return render(request, template_name='series.html', context=ctx)


# def series_list(request):
#     series_list = models.BookSeries.objects.all()
#     ctx = {
#         'series_list': series_list
#     }
#     return render(request, template_name='series_list.html', context=ctx)

src/refshelf/templates/refshelf/authors_confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить автора{% endblock %}
    
{% block h1 %} Вы действительно хотите удалить автора  {{ object.first_name }} {{ object.last_name }} из каталога?{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
     <input type="submit" value="Да, удалить" class="btn btn-danger">
     <a href="{% url 'refshelf:authors' %}" class="btn btn-warning">Нет, я передумал</a>
</form>

{% endblock %}

src/refshelf/templates/refshelf/authors_detail.html
{% extends "base.html" %}

{% block title %}Об авторе{% endblock %}
    
{% block h1 %}Автор: {{ object.first_name }} {{ object.last_name }}{% endblock %}
  
{% block content %}
{% if user.profile.sale_staff %}
<div class="my-1 d-flex flex-row">    
        <div class='p-1'><a href="{% url 'stmanager:author_update' object.pk %}">Редактировать</a></div>
        <div class='p-1'><a href="{% url 'stmanager:author_delete' object.pk %}">Удалить</a></div>    
</div>
{% endif %}
<div class="card" style="width: 18rem;">
    <img src=" {{ object.picture.url }}" class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text">{{ object.first_name }} {{ object.last_name }}</p>
    </div>
  </div>
<div class='mt-3'>
    <a class="btn btn-outline-primary" href="{% url 'refshelf:authors' %}">К списку авторов</a>    
</div>
{% endblock %}

src/refshelf/templates/refshelf/authors_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Добавить автора{% endblock %}
    
{% block h1 %}Добавить автора{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-group">
        {{ form|crispy }}
    </div>
    <div class='mt-3'>
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </div>    
</form>
{% endblock %}
  

src/refshelf/templates/refshelf/authors_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список авторов{% endblock %}
    
{% block h1 %}Список авторов:{% endblock %}
{% block content %}
 
<div class="row card-group">  
      {% for author in object_list %}
      <div class="col-3 mb-3">
        <div class="card border-primary h-100">
             <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
          <div class="card-body">
            <div class="card-text text-center">
            </div>
              <h4 class="card-title text-center"><a href="{% url 'refshelf:author' author.pk %}">{{ author }}</a></h4>
                <div class="text-center">
                  <h6 class="font-weight-bold ">
                  </h6>
                </div>
          </div>
        </div>
      </div>
      {% endfor %}
    
</div>
{% endblock %}

src/refshelf/templates/refshelf/bookseries_confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить серию{% endblock %}
    
{% block h1 %} Вы действительно хотите удалить серию {{ object.bookseries_name }} из каталога?{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
     <input type="submit" value="Да, удалить" class="btn btn-danger">
     <a href="{% url 'refshelf:publishers' %}" class="btn btn-warning">Нет, я передумал</a>
</form>

{% endblock %}

src/refshelf/templates/refshelf/bookseries_detail.html
{% extends "base.html" %}

{% block title %}О серии книг{% endblock %}
    
{% block h1 %}Серия: {{ object.series_name }}{% endblock %}
    
{% block content %}
{% if user.profile.sale_staff %}
<div class="my-1 d-flex flex-row">    
        <div class='p-1'><a href="{% url 'stmanager:series_update' object.pk %}">Редактировать</a></div>
        <div class='p-1'><a href="{% url 'stmanager:series_delete' object.pk %}">Удалить</a></div>    
</div>
{% endif %}
<div>
    {{ object.series_description}}
</div>
<div class='mt-3 text-center'>
    <a class="btn btn-outline-primary" href="{% url 'refshelf:serieses' %}">К списку серий</a>    
</div>
{% endblock %}
    

src/refshelf/templates/refshelf/genre_confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить жанр{% endblock %}
    
{% block h1 %} Вы действительно хотите удалить жанр  {{ object.genre_name }} из каталога?{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
     <input type="submit" value="Да, удалить" class="btn btn-danger">
     <a href="{% url 'refshelf:genres' %}" class="btn btn-warning">Нет, я передумал</a>
</form>

{% endblock %}

src/refshelf/templates/refshelf/genre_detail.html
{% extends "base.html" %}

{% block title %}О жанре{% endblock %}
    
{% block h1 %}Жанр: {{ object.genre_name }}{% endblock %}
    
{% block content %}
{% if user.profile.sale_staff %}
<div class="my-1 d-flex flex-row">    
        <div class='p-1'><a href="{% url 'stmanager:genre_update' object.pk %}">Редактировать</a></div>
        <div class='p-1'><a href="{% url 'stmanager:genre_delete' object.pk %}">Удалить</a></div>    
</div>
{% endif %}
<div>{{ object.genre_description}}</div>
<div class='mt-3'>
    <a class="btn btn-outline-primary" href="{% url 'refshelf:genres' %}">К списку жанров</a>    
</div>
{% endblock %}
  
  

src/refshelf/templates/refshelf/genre_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Добавить жанр{% endblock %}
    
{% block h1 %}Добавить жанр{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <div class="form-group">
        {{ form|crispy }}
    </div>
    <div class='mt-3'>
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </div>    
</form>
{% endblock %}
  

src/refshelf/templates/refshelf/genre_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список жанров{% endblock %}
    
{% block h1 %}Список жанров:{% endblock %}
{% block content %}

<div class="row card-group">
      {% for genre in object_list %}
      <div class="col-3 mb-3">
        <div class="card border-primary h-100">
             <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
          <div class="card-body">
            <div class="card-text text-center">
            </div>
              <h4 class="card-title text-center"><a href="{% url 'refshelf:genre' genre.pk %}">{{ genre }}</a></h4>
                <div class="text-center">
                  <h6 class="font-weight-bold ">
                  </h6>
                </div>
          </div>
        </div>
      </div>
      {% endfor %}
</div>
{% endblock %}
    

src/refshelf/templates/refshelf/publisher_confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить издательство{% endblock %}
    
{% block h1 %} Вы действительно хотите удалить издательство  {{ object.publisher_name }} из каталога?{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
     <input type="submit" value="Да, удалить" class="btn btn-danger">
     <a href="{% url 'refshelf:publishers' %}" class="btn btn-warning">Нет, я передумал</a>
</form>

{% endblock %}

src/refshelf/templates/refshelf/publisher_detail.html
{% extends "base.html" %}

{% block title %}Об издательстве{% endblock %}
    
{% block h1 %}Издательство: {{ object.publisher_name }}{% endblock %}
    
{% block content %}
{% if user.profile.sale_staff %}
<div class="my-1 d-flex flex-row">    
        <div class='p-1'><a href="{% url 'stmanager:publisher_update' object.pk %}">Редактировать</a></div>
        <div class='p-1'><a href="{% url 'stmanager:publisher_delete' object.pk %}">Удалить</a></div>    
</div>
{% endif %}
<div>{{ object.publisher_description}}</div>
<div class='mt-3'>
    <a class="btn btn-outline-primary" href="{% url 'refshelf:publishers' %}">К списку издательств</a>    
</div>
{% endblock %}
    

src/refshelf/templates/refshelf/publisher_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Добавить издательство{% endblock %}
    
{% block h1 %}Добавить издательство{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <div class="form-group">
        {{ form|crispy }}
    </div>
    <div class='mt-3'>
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </div>    
</form>
{% endblock %}
  

src/refshelf/templates/refshelf/publisher_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список издательств{% endblock %}
    
{% block h1 %}Список издательств:{% endblock %}
{% block content %}
<div class="row card-group">  
      {% for publisher in object_list %}
      <div class="col-3 mb-3">
        <div class="card border-primary h-100">
             <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
          <div class="card-body">
            <div class="card-text text-center">
            </div>
              <h4 class="card-title text-center"><a href="{% url 'refshelf:publisher' publisher.pk %}">{{ publisher }}</a></h4>
                <div class="text-center">
                  <h6 class="font-weight-bold ">
                  </h6>
                </div>
          </div>
        </div>
      </div>      
      {% endfor %}
</div>
{% endblock %}
  