src/books/urls.py
from django.urls import path

from books import views as book_views

app_name = 'books'

urlpatterns = [
    path('book/<int:pk>/', book_views.BookDetails.as_view(), name='book'),
    path('books/', book_views.BookList.as_view(), name='books'),
    #path('book_update/<int:pk>/', refshelf_views.AuthorUpdate.as_view(), name='author_update'),
    #path('book_delete/<int:pk>/', refshelf_views.AuthorDelete.as_view(), name='author_delete')
]

src/carts/urls.py
from django.urls import path

from carts import views as carts_views

app_name = 'carts'

urlpatterns = [
    path('', carts_views.CartView.as_view(), name='cart_detail'),
    path('delete-cart-item/<int:pk>', carts_views.DeleteCartItem.as_view(), name='delete-cart-item'),
    path('update-cart/', carts_views.UpdateCartView.as_view(), name='update-cart'),
]

src/csvf/urls.py
from django.urls import path
from .views import csv_import_view

app_name = 'csvf'

urlpatterns = [
    path('csv_import', csv_import_view, name='csv_import'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

#import for media files
from django.conf import settings
from django.conf.urls.static import static

#from refshelf import views as refshelf_views
from books import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refshelf/', include('refshelf.urls', namespace='refshelf')),
    path('users/', include('users.urls', namespace='users')),
    path('books/', include('books.urls', namespace='books')),
    path('csvf/', include('csvf.urls', namespace='csvf')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('stmanager/', include('stmanager.urls', namespace='stmanager')),
    path('', book_views.HomeView.as_view(), name='home'),
]

if settings.DEV_MODE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/refshelf/urls.py
from django.urls import path

from refshelf import views as refshelf_views

app_name = 'refshelf'

urlpatterns = [
    path('author/<int:pk>/', refshelf_views.AuthorDetails.as_view(), name='author'),
    path('authors/', refshelf_views.AuthorList.as_view(), name='authors'),
    path('genre/<int:pk>/', refshelf_views.GenreDetails.as_view(), name='genre'),
    path('genres/', refshelf_views.GenreList.as_view(), name='genres'),
    path('publisher/<int:pk>/', refshelf_views.PublisherDetails.as_view(), name='publisher'),
    path('publishers/', refshelf_views.PublisherList.as_view(), name='publishers'),
    path('series/<int:pk>/', refshelf_views.SeriesDetails.as_view(), name='series'),
    path('serieses/', refshelf_views.SeriesList.as_view(), name='serieses'),
]

src/stmanager/urls.py
from django.urls import path

from stmanager import views as manager_views

app_name = 'stmanager'

urlpatterns = [
    path('series_create/', manager_views.SeriesCreate.as_view(), name='series_create'),
    path('series_update/<int:pk>/', manager_views.SeriesUpdate.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', manager_views.SeriesDelete.as_view(), name='series_delete'),
    path('create_res/', manager_views.ViewOrders.as_view(), name='create_res'),
    path('publisher_create/', manager_views.PublisherCreate.as_view(), name='publisher_create'),
    path('publisher_update/<int:pk>/', manager_views.PublisherUpdate.as_view(), name='publisher_update'),
    path('publisher_delete/<int:pk>/', manager_views.PublisherDelete.as_view(), name='publisher_delete'),
    path('genre_create/', manager_views.GenreCreate.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', manager_views.GenreUpdate.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', manager_views.GenreDelete.as_view(), name='genre_delete'),
    path('author_create/', manager_views.AuthorCreate.as_view(), name='author_create'),
    path('author_update/<int:pk>/', manager_views.AuthorUpdate.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', manager_views.AuthorDelete.as_view(), name='author_delete'),
    path('book_create/', manager_views.BookCreate.as_view(), name='book_create'),
    path('book_update/<int:pk>/', manager_views.BookUpdate.as_view(), name='book_update'),
    path('book_delete/<int:pk>/', manager_views.BookDelete.as_view(), name='book_delete'),
    path('cart_ordered/<int:pk>/', manager_views.CartItemsDetail.as_view(), name='cart_ordered'),
    path('change_order_status/<int:pk>/', manager_views.UpdateOrderStatus.as_view(), name='change_order_status'),
]

src/users/urls.py
from django.urls import path
from stmanager.views import CartItemsDetail
from users import views as users_views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password/', users_views.ModifyPassword.as_view(template_name='users/change-password.html'), name='password'),
    path('password-success/', users_views.password_success, name='password-success'),
    path('become-manager/', users_views.info_become_manager, name='become-manager'),
    path('user_cart_ordered/<int:pk>/', users_views.CartItemsDetail.as_view(), name='user_cart_ordered'),
]

src/books/models.py
from django.db import models
from django.urls import reverse
from refshelf import models as refbook



class Binding(models.Model):
    binding_type = models.CharField(
        verbose_name='Переплет',
        max_length=100
    )

    def __str__(self) -> str:
        return f' {self.binding_type}'   

    class Meta:
        verbose_name = 'Переплет'
        verbose_name_plural = 'Переплеты'


class Book(models.Model):
    
    class AgeRestr(models.Model):
        UNDERSIX = '0+'
        ABOVESIX = '6+'
        ABOVETWELVE = '12+'
        ABOVESIXTEEN ='16+'
        ABOVEEIGHTTEEN ='18+'

        AGE_CHOICES = [
            (UNDERSIX, '0+'),
            (ABOVESIX, '6+'),
            (ABOVETWELVE, '12+'),
            (ABOVESIXTEEN, '16+'),
            (ABOVEEIGHTTEEN, '18+')
        ]
    
    class BookFormat(models.Model):
        SUPERBIG = 'Сверхкрупный'
        BIG = 'Крупный'
        INTERM = 'Средний'
        SMALL ='Малый'
        SUPERSMALL ='Сверхмалый'

        FORMAT_CHOICES = [
            (SUPERBIG, 'Сверхкрупный'),
            (BIG, 'Крупный'),
            (INTERM, 'Средний'),
            (SMALL, 'Малый'),
            (SUPERSMALL, 'Сверхмалый')
        ]

    book_title = models.CharField(
        verbose_name='Название книги', 
        max_length=250
        )
    cover_picture = models.ImageField(
        verbose_name='Фото обложки',
        upload_to ='book//%Y/%m/%d/',
        blank=True, 
        null=True
    )
    book_price = models.DecimalField(
        verbose_name='Стоимость книги, BYN', 
        max_digits=5,
        decimal_places = 2
        )
    book_authors = models.ManyToManyField(
        refbook.Authors,
        verbose_name='Автор(ы)',
        related_name='books'
    )
    book_series = models.ForeignKey(
        refbook.BookSeries,
        on_delete=models.RESTRICT,
        verbose_name='Серия книг',
        related_name='books',
        blank=True, 
        null=True
    )
    book_genres = models.ManyToManyField(
        refbook.Genre,
        verbose_name='Жанр(ы)',
        related_name='books'
    )
    book_year = models.PositiveSmallIntegerField(
        verbose_name='Год издания'
    )
    book_pages = models.PositiveSmallIntegerField(
        verbose_name='Количество страниц'
    )
    book_icbn = models.CharField(
        verbose_name='Номер ISBN',
        max_length=200        
    )
    book_weight = models.PositiveSmallIntegerField(
        verbose_name='Вес книги'
    )
    book_publisher = models.ForeignKey(
        refbook.Publisher,
        on_delete=models.RESTRICT,
        verbose_name='Издательство',
        related_name='books'
    )
    book_format = models.CharField(
        verbose_name='Формат книги',
        max_length=25,
        choices=BookFormat.FORMAT_CHOICES,
        default=BookFormat.INTERM
    )
    book_bindings = models.ForeignKey(
        Binding,
        on_delete=models.RESTRICT,
        verbose_name='Переплет',
        related_name='books'
    )
    book_quantity = models.PositiveIntegerField(
        verbose_name='Количество книг на складе'
    )
    is_available = models.BooleanField(
        verbose_name='В наличии',
        default=True
    )
    is_recommended = models.BooleanField(
        verbose_name='Рекомендуемый товар',
        default=False,
        blank=True, 
        null=True
    )
    age_restrictions = models.CharField(
        verbose_name='Возрастные ограничения',
        max_length=3,
        choices=AgeRestr.AGE_CHOICES,
        default=AgeRestr.UNDERSIX
    )
    book_rating = models.IntegerField(
        verbose_name='Рейтинг',
        choices=((i,i) for i in range(11)) 
    )
    book_created = models.DateTimeField(
        verbose_name='Дата создания в каталоге',
        auto_now=False,
        auto_now_add=True
    )
    book_modified = models.DateTimeField(
        verbose_name='Дата последнего изменения',
        auto_now=True,
        auto_now_add=False
    )

    def __str__(self) -> str:        
        return "%s (%s)" %(
            self.book_title,
            ", ".join(str(author) for author in self.book_authors.all()),
        )

    def get_absolute_url(self):
        return reverse('books:book', kwargs={'pk': self.pk})    

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

src/books/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView
)
from . import models
from carts.models import CartItems
from django.db.models import Q
from django.db.models import Sum, Count
import random

# Create your views here.


class BookDetails(DetailView):
    model = models.Book


    def get_context_data(self, **kwargs):
        context = super(BookDetails, self).get_context_data(**kwargs)
        genres = self.get_object().book_genres.all()
        if genres.count() == 1:
            genres1 = self.get_object().book_genres.all()[0]
            filtered_book = models.Book.objects.filter(
            Q(book_genres=genres1)
            ).exclude(pk=self.get_object().pk)
        else:
            genres1 = self.get_object().book_genres.all()[0]
            genres2 = self.get_object().book_genres.all()[1]
            filtered_book = models.Book.objects.filter(
            Q(book_genres=genres1) | Q(book_genres=genres2)
            ).exclude(pk=self.get_object().pk)
        
        if filtered_book.count() >= 3:    
            rand_filt_book = random.sample(list(filtered_book), 3)
            context['related_items'] = rand_filt_book
        else: 
            context['related_items'] = filtered_book
        return context

class BookList(ListView):
    model = models.Book

    def get_queryset(self):
        qs = super().get_queryset()
        bsearch = self.request.GET.get('bsearch')
        if bsearch:
            return qs.filter(Q(book_title__icontains=bsearch) | Q(book_authors__last_name__icontains=bsearch) | Q(book_authors__first_name__icontains=bsearch)) 
        return qs

class HomeView(TemplateView):
    template_name='books/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_books'] = models.Book.objects.all().order_by('-id')[:3]
        context['recommended_books'] = models.Book.objects.all().filter(is_recommended=True)
        context['total_books'] = models.Book.objects.aggregate(tot = Count('book_title'))
        context['sold_books'] = models.Book.objects.annotate(tot = Sum('cartitems__quantity')).order_by('-tot')[:3]

        return context

src/books/templates/books/book_confirm_delete.html
{% extends "base.html" %}

{% block title %}Удалить книгу из каталога{% endblock %}
    
{% block h1 %} Вы действительно хотите удалить книгу  {{ object.book_title }} из каталога?{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
     <input type="submit" value="Да, удалить" class="btn btn-danger">
     <a href="{% url 'books:books' %}" class="btn btn-warning">Нет, я передумал</a>
</form>

{% endblock %}

src/books/templates/books/book_detail.html
{% extends "book_base.html" %}
{% load static %}

{% block title %}Описание товара{% endblock %}

{% block h1 %}
  Книга: <h2>{{ object.book_title }}</h2> </br>
  <small>
    {% for obj in object.book_authors.all %}
          <a href="{% url 'refshelf:author' obj.pk %}">{{ obj }}</a>
          {% endfor %}
  </small> 
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="card" style="width: 18rem;">
      {% if book.cover_picture %}
        <img alt="" class="card-img-top card-img-adjust" src="{{ book.cover_picture.url }}" />
      {% else %}
        <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
      {% endif %}
        <div class="card-body">
          <p class="card-text"></p>
        </div>
    </div>
  </div>
  <div class="col-sm-6">
    {% if object.is_available %}
    <div class="p-2 text-center bcg-block-3">
      <p>ЭТА КНИГА ЕСТЬ В НАЛИЧИИ!</p>
      <p>На складе осталось {{ object.book_quantity }} шт.</p>
    </div>
    <div class='mt-4'>
      <p class="text-center"><strong>ЦЕНА: {{ object.book_price }} BYN</strong> </p>  
    </div>
    <div class="mt-5 text-center">
      <a href="{% url 'carts:cart_detail' %}?book_id={{ book.pk }}" class='btn btn-danger'>В корзину</a>
    </div>
    {% else %}
    <div class="alert alert-danger text-center">
      ТОВАР ОТСУТСТВУЕТ
    </div>
    {% endif %}
</div>
  <div class="row">
    <div class="col-sm-8">
      <div class='pb-2'>Жанр(ы): 
        {% for obj in object.book_genres.all %}
        <a href="{% url 'refshelf:genre' obj.pk %}">{{ obj }}</a>
        {% endfor %}
      </div>
      {% if object.book_series %}
      <div class='pb-2'>
        Книга из серии книг {{ object.book_series }}
      </div>
      {% endif %}
      <div class='pb-2'>Год издания: 
        {{ object.book_year }}
      </div>
      <div class='pb-2'>ISBN: 
        {{ object.book_icbn }}
      </div>
      <div class='pb-2'>Издательство: 
        {{ object.book_publisher }}
      </div>
      <div class='pb-2'>Количество страниц: 
        {{ object.book_pages }}
      </div>
      <div class='pb-2'>Переплет: 
        {{ object.book_bindings }}
      </div>
      <div class='pb-2'>Формат книги: 
        {{ object.book_format }}
      </div>
      <div class='pb-2'>Вес книги: 
        {{ object.book_weight }} кг
      </div>
      <div class='pb-2'>Возрастные ограничения: 
        {{ object.age_restrictions }}
      </div>
      <div class='pb-2'>Рейтинг: 
        {{ object.book_rating }}
      </div>
      <div class='mt-6 text-center'>
        <a class="btn btn-outline-primary" href="{% url 'books:books' %}">К списку товаров</a>    
    </div>
    </div>
  </div>   
  
</div>
{% endblock %}

{% block sideblock %}
    {% if user.profile.sale_staff %}
    <div class="">    
        <h5>Управление товаром</h5>
              <div class='p-1'><a href="{% url 'stmanager:book_update' object.pk %}" class="btn btn-outline-warning">Редактировать</a></div>
              <div class='p-1'><a href="{% url 'stmanager:book_delete' object.pk %}" class="btn btn-outline-danger">Удалить</a></div>    
    </div>
    {% endif %}
    <div class="mt-2">
      {% if related_items %}
        <h4>Возможно Вас заинтересует:</h4>
        <div class="d-flex flex-column align-items-center p-2">          
            {% for obj in related_items %}
            <div class="card mb-2" style="width: 10rem;">
              {% if obj.cover_picture %}
                <img alt="" class="card-img-top card-img-adjust" src="{{ obj.cover_picture.url }}" />
              {% else %}
                <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
              {% endif %}
                <div class="card-body">
                  <p class="card-text">
                    <a href="{% url 'books:book' obj.pk %}">{{ obj.book_title }}</a>
                  </p>
                </div>
            </div>
            {% endfor %}
          
        </div>
      {% endif %}
    </div>

{% endblock %}

src/books/templates/books/book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Добавить новую книгу{% endblock %}
    
{% block h1 %}Добавить новую книгу{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{ form|crispy }}
    </div>
    <div class='mt-3'>
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </div>    
</form>
{% endblock %}

src/books/templates/books/book_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Каталог товаров{% endblock %}
    
{% block h1 %}КАТАЛОГ КНИГ:{% endblock %}
{% block content %}
<div class="row card-group">
  {% for book in object_list|dictsort:"book_title" %}
    <div class="col-4 mb-3">
      <div class="card border-primary h-100">
          {% if book.cover_picture %}
              <img alt="" class="card-img-top card-img-adjust" src="{{ book.cover_picture.url }}" />
              {% else %}
              <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
          {% endif %}
        <div class="card-body">
          <div class="card-text text-center">
            {% for obj in book.book_authors.all %}
                {{ obj }}</br>
            {% endfor %}
          </div>
            <h5 class="card-title text-center">
              <a href="{% url 'books:book' book.pk %}" class='book-title-link'>{{ book.book_title }}</a>
            </h5>
                <div class="card-text text-center">
                  {% for obj in book.book_genres.all %}
                      {{ obj }}</br>
                  {% endfor %}
                </div>
        </div>
        <div class="card-footer text-center">
          <div class=''>
            <h6 class="font-weight-bold ">
                <strong>
                    {% if book.book_price %}
                      {{ book.book_price}} BYN
                    {% endif %}
                </strong>
            </h6>
          </div>
          <a href="{% url 'carts:cart_detail' %}?book_id={{ book.pk }}" class='btn btn-danger'>В корзину</a>
        </div>
      </div>
    </div>
    {% empty %}
    <h4>Поиск не дал результатов</h4>
    <small>Совет: Учитывайте регистр в вашем поисковом запросе</small>
  {% endfor %}
  </div>
{% endblock %}

src/books/templates/books/home.html
{% extends "home_base.html" %}
{% load static %}

{% block title %}Книжный магазин{% endblock %}
{% block h1 %}Добро пожаловать в электронный книжный магазин! {% endblock %}    

{% block hero-content %}
<h3>В нашем магазине сейчас {{total_books.tot}} книг</h3>
<p>Здесь Ваши любмые книги! Легко найти и заказать!</p>
<div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
    <a href="{% url 'books:books' %}"><button type="button" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Каталог</button></a>
    <a href="{% url 'users:become-manager' %}"><button type="button" class="btn btn-outline-light btn-lg px-4">Стать сотрудником</button></a>
  </div>
{% endblock %}

{% block content %}
<div class="row mt-4 text-center">
    <h2>ПОСЛЕДНИЕ ПОСТУПЛЕНИЯ</h2>
</div>
<div class="row card-group">
    {% for book in latest_books %}
        <div class="col-4 mb-3 mt-4">
            <div class="card border-primary h-100">
                {% if book.cover_picture %}
                    <img alt="" class="card-img-top card-img-adjust" src="{{ book.cover_picture.url }}" />
                    {% else %}
                    <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
                {% endif %}
                <div class="card-body">
                    <div class="card-text text-center">
                        {% for obj in book.book_authors.all %}
                            {{ obj }}</br>
                        {% endfor %}
                      </div>
                        <h4 class="card-title text-center">
                            <b><a href="{% url 'books:book' book.pk %}" class='book-title-link'>{{ book.book_title }}</a></b>
                        </h4>
                            <div class="card-text text-center">
                              {% for obj in book.book_genres.all %}
                                  {{ obj }}</br>
                              {% endfor %}
                            </div>
                </div>
                <div class="card-footer text-center">
                    <div class=''>
                      <h6 class="font-weight-bold ">
                          <strong>
                              {% if book.book_price %}
                                {{ book.book_price}} BYN
                              {% endif %}
                          </strong>
                      </h6>
                    </div>
                    <a href="{% url 'carts:cart_detail' %}?book_id={{ book.pk }}" class='btn btn-danger'>В корзину</a>
                  </div>
            </div>    
        </div>
    {% endfor %}
</div>
<div class="row mt-4 text-center">
    <h2>ЧАЩЕ ВСЕГО ЗАКАЗЫВАЮТ</h2>
    <div class="row card-group">
    {% for book in sold_books %}
            <div class="col-4 mb-3 mt-4">
                <div class="card border-primary h-100">
                    {% if book.cover_picture %}
                        <img alt="" class="card-img-top card-img-adjust" src="{{ book.cover_picture.url }}" />
                        {% else %}
                        <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
                    {% endif %}
                    <div class="card-body">
                        <div class="card-text text-center">
                            {% for obj in book.book_authors.all %}
                                {{ obj }}</br>
                            {% endfor %}
                          </div>
                            <h4 class="card-title text-center">
                                <b><a href="{% url 'books:book' book.pk %}" class='book-title-link'>{{ book.book_title }}</a></b>
                            </h4>
                            <div class="card-text text-center">
                                {% for obj in book.book_genres.all %}
                                    {{ obj }}</br>
                                {% endfor %}
                            </div>
                    </div>
                    <div class="card-footer text-center">
                        <div class=''>
                          <h6 class="font-weight-bold ">
                              <strong>
                                  {% if book.book_price %}
                                    {{ book.book_price}} BYN
                                  {% endif %}
                              </strong>
                          </h6>
                        </div>
                        <a href="{% url 'carts:cart_detail' %}?book_id={{ book.pk }}" class='btn btn-danger'>В корзину</a></br>
                        <small>Заказано {{ book.tot }} шт.</small>
                      </div>
                </div>    
            </div>
    {% endfor %}
    </div>
</div>
<div class="row mt-4 text-center">
    <h2>РЕКОМЕНДУЕМ ЗАКАЗАТЬ</h2>
</div>
<div class="row card-group">
    {% for book in recommended_books %}
        <div class="col-4 mb-3 mt-4">
            <div class="card border-primary h-100">
                {% if book.cover_picture %}
                    <img alt="" class="card-img-top card-img-adjust" src="{{ book.cover_picture.url }}" />
                    {% else %}
                    <img alt="" class="card-img-top card-img-adjust" src="{% static 'img/blank-book-cover.png' %}" />
                {% endif %}
                <div class="card-body">
                    <div class="card-text text-center">
                        {% for obj in book.book_authors.all %}
                            {{ obj }}</br>
                        {% endfor %}
                      </div>
                        <h4 class="card-title text-center">
                            <b><a href="{% url 'books:book' book.pk %}" class='book-title-link'>{{ book.book_title }}</a></b>
                        </h4>
                        <div class="card-text text-center">
                            {% for obj in book.book_genres.all %}
                                {{ obj }}</br>
                            {% endfor %}
                        </div>
                </div>
                <div class="card-footer text-center">
                    <div class=''>
                      <h6 class="font-weight-bold ">
                          <strong>
                              {% if book.book_price %}
                                {{ book.book_price}} BYN
                              {% endif %}
                          </strong>
                      </h6>
                    </div>
                    <a href="{% url 'carts:cart_detail' %}?book_id={{ book.pk }}" class='btn btn-danger'>В корзину</a>
                  </div>
            </div>    
        </div>
    {% endfor %}
</div>
{% endblock %}