src/csvf/urls.py
from django.urls import path
from .views import csv_import_view

app_name = 'csvf'

urlpatterns = [
    path('csv_import', csv_import_view, name='csv_import'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

#import for media files
from django.conf import settings
from django.conf.urls.static import static

#from refshelf import views as refshelf_views
from books import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refshelf/', include('refshelf.urls', namespace='refshelf')),
    path('users/', include('users.urls', namespace='users')),
    path('books/', include('books.urls', namespace='books')),
    path('csvf/', include('csvf.urls', namespace='csvf')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('stmanager/', include('stmanager.urls', namespace='stmanager')),
    path('', book_views.HomeView.as_view(), name='home'),
]

if settings.DEV_MODE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/stmanager/urls.py
from django.urls import path

from stmanager import views as manager_views

app_name = 'stmanager'

urlpatterns = [
    path('series_create/', manager_views.SeriesCreate.as_view(), name='series_create'),
    path('series_update/<int:pk>/', manager_views.SeriesUpdate.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', manager_views.SeriesDelete.as_view(), name='series_delete'),
    path('create_res/', manager_views.ViewOrders.as_view(), name='create_res'),
    path('publisher_create/', manager_views.PublisherCreate.as_view(), name='publisher_create'),
    path('publisher_update/<int:pk>/', manager_views.PublisherUpdate.as_view(), name='publisher_update'),
    path('publisher_delete/<int:pk>/', manager_views.PublisherDelete.as_view(), name='publisher_delete'),
    path('genre_create/', manager_views.GenreCreate.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', manager_views.GenreUpdate.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', manager_views.GenreDelete.as_view(), name='genre_delete'),
    path('author_create/', manager_views.AuthorCreate.as_view(), name='author_create'),
    path('author_update/<int:pk>/', manager_views.AuthorUpdate.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', manager_views.AuthorDelete.as_view(), name='author_delete'),
    path('book_create/', manager_views.BookCreate.as_view(), name='book_create'),
    path('book_update/<int:pk>/', manager_views.BookUpdate.as_view(), name='book_update'),
    path('book_delete/<int:pk>/', manager_views.BookDelete.as_view(), name='book_delete'),
    path('cart_ordered/<int:pk>/', manager_views.CartItemsDetail.as_view(), name='cart_ordered'),
    path('change_order_status/<int:pk>/', manager_views.UpdateOrderStatus.as_view(), name='change_order_status'),
]

src/stmanager/models.py
from django.db import models

# Create your models here.

src/stmanager/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.auth import get_user_model
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
    DetailView
)
from refshelf import models as refmodels
from books import models as bookmodels
from orders import models as ordermodels
from carts import models as cartmodels
from users import models as usermodel


#Edit Authors

class AuthorCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView ):
    model = refmodels.Authors
    fields = ['first_name', 'last_name', 'picture']

    def test_func(self):
        return self.request.user.profile.sale_staff == True 

class AuthorUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = refmodels.Authors
    fields = ['first_name', 'last_name', 'picture']

    def test_func(self):
        return self.request.user.profile.sale_staff == True 

class AuthorDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = refmodels.Authors
    success_url = reverse_lazy('refshelf:authors')

    def test_func(self):
        return self.request.user.profile.sale_staff == True 

#Edit Genre

class GenreCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = refmodels.Genre
    fields = ['genre_name', 'genre_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True 

class GenreUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = refmodels.Genre
    fields = ['genre_name', 'genre_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class GenreDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = refmodels.Genre
    success_url = reverse_lazy('refshelf:genres')

    def test_func(self):
        return self.request.user.profile.sale_staff == True

#Edit Publisher

class PublisherCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = refmodels.Publisher
    fields = ['publisher_name', 'publisher_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class PublisherUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = refmodels.Publisher
    fields = ['publisher_name', 'publisher_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class PublisherDelete(LoginRequiredMixin, UserPassesTestMixin,  DeleteView):
    model = refmodels.Publisher
    success_url = reverse_lazy('refshelf:publishers')

    def test_func(self):
        return self.request.user.profile.sale_staff == True

#Edit Series

class SeriesCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = refmodels.BookSeries
    fields = ['series_name', 'series_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class SeriesUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = refmodels.BookSeries
    fields = ['series_name', 'series_description']

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class SeriesDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = refmodels.BookSeries
    success_url = reverse_lazy('refshelf:serieses')

    def test_func(self):
        return self.request.user.profile.sale_staff == True


#Edit book

class BookCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = bookmodels.Book
    fields = '__all__'

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class BookUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = bookmodels.Book
    fields = '__all__'

    def test_func(self):
        return self.request.user.profile.sale_staff == True

class BookDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = bookmodels.Book
    success_url = reverse_lazy('books:books')

    def test_func(self):
        return self.request.user.profile.sale_staff == True

# def resource_create(request):
#     return render(request, 'stmanager/create_res.html')



class ViewOrders(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = ordermodels.Order
    template_name = 'stmanager/create_res.html'

    def test_func(self):
        return self.request.user.profile.sale_staff == True

    def get_queryset(self):
        qs = super().get_queryset()
        status_chk = self.request.GET.get('status_chk')
        print(status_chk)
        if status_chk:
            return qs.filter(order_status__contains=status_chk) 
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = usermodel.Profile.objects.all()
        return context

class UpdateOrderStatus(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = ordermodels.Order
    fields = ['order_status']
    template_name = 'stmanager/order_status_form.html'

    def test_func(self):
        return self.request.user.profile.sale_staff == True


class CartItemsDetail(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = cartmodels.Cart
    template_name='stmanager/cart_ordered.html'

    def test_func(self):
        return self.request.user.profile.sale_staff == True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = int(self.kwargs.get('pk'))
        context['order_detail'] = ordermodels.Order.objects.get(cart=cart_id)
        return context

src/stmanager/templates/stmanager/cart_ordered.html
{% extends "base.html" %}


{% block title %}Детали заказа{% endblock %}
    
{% block h1 %}Детали заказа №{{order_detail.pk}}{% endblock %}
{% block content %}
 
<div class="">
    <div class="row">
        <div class='col-md-8'>
            <p>
                {% if object.customer %}
                    <b>{{object}} - Клиент: {{object.customer}} </b>
                {% else %}
                    <b>{{object}} - Заказ сделал анонимный пользователь</b>
                {% endif %} 
            </p>
            <p>
                Контактная информация клиента (тел): {{order_detail.contact_info}}
            </p>
        </div>
        <div class='col-md-4'>
            <div class='p-1 text-center {{order_detail.status_color}}'>
                Статус заказа: {{order_detail.order_status}}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="mt-1">
                <p>Выбраны следующие товары для заказа:</p>
        </div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Товар</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Стоимость, за шт.</th>
                </tr>
                </thead>
                <tbody>           
                    {% for line in object.cart_items.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ line.book }}</td>
                        <td>{{ line.quantity }}</td>
                        <td>{{ line.item_total_price }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3"><b>Суммарная стоимость:</b></td>
                        <td><b>{{ object.cart_total_price }}</b></td>
                        
                    </tr>
                </tbody>
            </table>
            <div class='mt-2'>
                <a href="{% url 'stmanager:change_order_status' object.pk %}" class="btn btn-xs btn-warning">Изменить статус</a>
                <a href="{% url 'stmanager:create_res' %}" class="btn btn-xs btn-success">Вернуться в панель управления</a>
            </div>
        </div>
    </div>
    
    
</div>
{% endblock %}

src/stmanager/templates/stmanager/create_res.html
{% extends "base.html" %}


{% block title %}Управление магазином {% endblock %}

{% block h1 %}Управление контентом и заказами{% endblock %}

{% block content %}
{% if user.profile.sale_staff %}
<div class='row mb-3'>
    <div class="col-md-12">
        <div class="p-3 mb-3 text-center text-light bcg-block">
        <h5>Добавить ресурс:</h5>
        </div>
        <div class="btn-group btn-group-sp" role="group" aria-label="add-resource">
            <a href="{% url 'stmanager:book_create' %}" class="btn btn-outline-primary btn-block">Добавить новую книгу</a>
            <a href="{% url 'stmanager:series_create' %}" class="btn btn-outline-primary btn-block">Добавить новую серию книг</a>
            <a href="{% url 'stmanager:publisher_create' %}" class="btn btn-outline-primary btn-block">Добавить новое издательство</a>
            <a href="{% url 'stmanager:genre_create' %}" class="btn btn-outline-primary btn-block">Добавить новый жанр</a>
            <a href="{% url 'stmanager:author_create' %}" class="btn btn-outline-primary btn-block">Добавить нового автора</a>

        </div>
    </div>
</div>
<div class='row'>
    <div class="col-md-12">
        <div class="p-3 mb-3 text-light text-center bcg-block">
            <h5>Пользователи:</h5>
        </div>
        <div class="mt-2">
            <p>На сайте зарегистрировано {{ users|length }} пользователей</p>
            <p></p>
        </div>
    </div>
</div>        
<div class='row'>
    <div class="col-md-12">
        <div class="p-3 mb-3 text-light text-center bcg-block">
            <h5>Заказы в магазине:</h5>
        </div>
        <div class="mt-2">
            <form action="{% url 'stmanager:create_res' %}#filter-form" class="d-flex" id="filter-form">

                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="inlineradio1" value="" name="status_chk">
                    <label class="form-check-label" for="inlineradio1">Все</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="inlineradio2" value="Новый" name="status_chk">
                    <label class="form-check-label" for="inlineradio2">Новые</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="inlineradio3" value="В обработке" name="status_chk">
                    <label class="form-check-label" for="inlineradio3">В обработке</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="inlineradio3" value="Исполненный" name="status_chk">
                    <label class="form-check-label" for="inlineradio3">Исполненные</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="inlineradio4" value="Неудавшийся" name="status_chk">
                    <label class="form-check-label" for="inlineradio4">Неудавшиеся</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <button class="btn btn-sm btn-primary" type="submit" >Фильтровать</button>
                  </div>
            </form>
        </div>
        <div class="mt-2">
            <table class="table table-bordered" id="order-table">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Заказ</th>
                    <th scope="col">Клиент</th>
                    <th scope="col">Контакт</th>
                    <th scope="col">Дата создания</th>
                    <th scope="col">Дата изменения</th>
                    <th scope="col">Статус</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class='order-list'>           
                    {% for line in object_list %}
                    <tr class="{% cycle 'table-row1' 'table-row2' %}">
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'stmanager:cart_ordered' line.cart.pk %}">{{ line.cart}}</a>
                        </td>
                        <td>{{ line.cart.customer }}</td>
                        <td>{{ line.contact_info }}</td>
                        <td>{{line.order_created|date:"SHORT_DATE_FORMAT"}}</td>
                        <td>{{line.order_modified|date:"SHORT_DATE_FORMAT"}}</td>
                        <td>{{line.order_status}}</td>
                        <td>
                            <a href="{% url 'stmanager:change_order_status' line.pk %}" class="btn btn-sm {% cycle 'btn-light' 'btn-outline-secondary'  %}">Изменить статус</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endif %}

{% endblock %}

src/stmanager/templates/stmanager/order_status_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Статус заказа{% endblock %}
    
{% block h1 %}Изменить статус заказа{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form|crispy }}
    </div>
    <div class='mt-3'>
        <input type="submit" class="btn btn-primary" value="Сохранить">
    </div>    
</form>
{% endblock %}
  