src/books/urls.py
from django.urls import path

from books import views as book_views

app_name = 'books'

urlpatterns = [
    path('book/<int:pk>/', book_views.BookDetails.as_view(), name='book'),
    path('books/', book_views.BookList.as_view(), name='books'),
    #path('book_update/<int:pk>/', refshelf_views.AuthorUpdate.as_view(), name='author_update'),
    #path('book_delete/<int:pk>/', refshelf_views.AuthorDelete.as_view(), name='author_delete')
]

src/carts/urls.py
from django.urls import path

from carts import views as carts_views

app_name = 'carts'

urlpatterns = [
    path('', carts_views.CartView.as_view(), name='cart_detail'),
    path('delete-cart-item/<int:pk>', carts_views.DeleteCartItem.as_view(), name='delete-cart-item'),
    path('update-cart/', carts_views.UpdateCartView.as_view(), name='update-cart'),
]

src/csvf/urls.py
from django.urls import path
from .views import csv_import_view

app_name = 'csvf'

urlpatterns = [
    path('csv_import', csv_import_view, name='csv_import'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

#import for media files
from django.conf import settings
from django.conf.urls.static import static

#from refshelf import views as refshelf_views
from books import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('refshelf/', include('refshelf.urls', namespace='refshelf')),
    path('users/', include('users.urls', namespace='users')),
    path('books/', include('books.urls', namespace='books')),
    path('csvf/', include('csvf.urls', namespace='csvf')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('stmanager/', include('stmanager.urls', namespace='stmanager')),
    path('', book_views.HomeView.as_view(), name='home'),
]

if settings.DEV_MODE:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/refshelf/urls.py
from django.urls import path

from refshelf import views as refshelf_views

app_name = 'refshelf'

urlpatterns = [
    path('author/<int:pk>/', refshelf_views.AuthorDetails.as_view(), name='author'),
    path('authors/', refshelf_views.AuthorList.as_view(), name='authors'),
    path('genre/<int:pk>/', refshelf_views.GenreDetails.as_view(), name='genre'),
    path('genres/', refshelf_views.GenreList.as_view(), name='genres'),
    path('publisher/<int:pk>/', refshelf_views.PublisherDetails.as_view(), name='publisher'),
    path('publishers/', refshelf_views.PublisherList.as_view(), name='publishers'),
    path('series/<int:pk>/', refshelf_views.SeriesDetails.as_view(), name='series'),
    path('serieses/', refshelf_views.SeriesList.as_view(), name='serieses'),
]

src/stmanager/urls.py
from django.urls import path

from stmanager import views as manager_views

app_name = 'stmanager'

urlpatterns = [
    path('series_create/', manager_views.SeriesCreate.as_view(), name='series_create'),
    path('series_update/<int:pk>/', manager_views.SeriesUpdate.as_view(), name='series_update'),
    path('series_delete/<int:pk>/', manager_views.SeriesDelete.as_view(), name='series_delete'),
    path('create_res/', manager_views.ViewOrders.as_view(), name='create_res'),
    path('publisher_create/', manager_views.PublisherCreate.as_view(), name='publisher_create'),
    path('publisher_update/<int:pk>/', manager_views.PublisherUpdate.as_view(), name='publisher_update'),
    path('publisher_delete/<int:pk>/', manager_views.PublisherDelete.as_view(), name='publisher_delete'),
    path('genre_create/', manager_views.GenreCreate.as_view(), name='genre_create'),
    path('genre_update/<int:pk>/', manager_views.GenreUpdate.as_view(), name='genre_update'),
    path('genre_delete/<int:pk>/', manager_views.GenreDelete.as_view(), name='genre_delete'),
    path('author_create/', manager_views.AuthorCreate.as_view(), name='author_create'),
    path('author_update/<int:pk>/', manager_views.AuthorUpdate.as_view(), name='author_update'),
    path('author_delete/<int:pk>/', manager_views.AuthorDelete.as_view(), name='author_delete'),
    path('book_create/', manager_views.BookCreate.as_view(), name='book_create'),
    path('book_update/<int:pk>/', manager_views.BookUpdate.as_view(), name='book_update'),
    path('book_delete/<int:pk>/', manager_views.BookDelete.as_view(), name='book_delete'),
    path('cart_ordered/<int:pk>/', manager_views.CartItemsDetail.as_view(), name='cart_ordered'),
    path('change_order_status/<int:pk>/', manager_views.UpdateOrderStatus.as_view(), name='change_order_status'),
]

src/users/urls.py
from django.urls import path
from stmanager.views import CartItemsDetail
from users import views as users_views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password/', users_views.ModifyPassword.as_view(template_name='users/change-password.html'), name='password'),
    path('password-success/', users_views.password_success, name='password-success'),
    path('become-manager/', users_views.info_become_manager, name='become-manager'),
    path('user_cart_ordered/<int:pk>/', users_views.CartItemsDetail.as_view(), name='user_cart_ordered'),
]

src/refshelf/models.py
from django.db import models
from django.urls import reverse


class Authors(models.Model):
    first_name = models.CharField(
        verbose_name='Имя автора', 
        max_length=20
        )
    last_name = models.CharField(
        verbose_name='Фамилия автора', 
        max_length=20
        )

    picture = models.ImageField(
        verbose_name='Фото автора',
        upload_to ='authors//%Y/%m/%d/'
    )

    def __str__(self) -> str:
        return f' {self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('refshelf:author', kwargs={'pk': self.pk})    

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

class Genre(models.Model):
    genre_name = models.CharField(
        verbose_name='Название жанра',
        max_length=20
    )
    genre_description = models.TextField(
        verbose_name='Описание жанра',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f'{self.genre_name}'

    def get_absolute_url(self):
        return reverse('refshelf:genre', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

class Publisher(models.Model):
    publisher_name = models.CharField(
        verbose_name='Издательство',
        max_length=20
    )
    publisher_description = models.TextField(
        verbose_name='Информация об издательстве',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f' {self.publisher_name}'

    def get_absolute_url(self):
        return reverse('refshelf:publisher', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Издательство'
        verbose_name_plural = 'Издательства'

class BookSeries(models.Model):
    series_name = models.CharField(
        verbose_name='Серия',
        max_length=100
    )
    series_description = models.TextField(
        verbose_name='Описание серии',
        blank=True,
        null=True
    )
    def __str__(self) -> str:
        return f' {self.series_name}'

    def get_absolute_url(self):
        return reverse('refshelf:series', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Серия'
        verbose_name_plural = 'Серии'

src/refshelf/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
)
from . import models 

# Create your views here.

class AuthorDetails(DetailView):
    model = models.Authors

class AuthorList(ListView):
    model = models.Authors

class GenreDetails(DetailView):
    model = models.Genre

class GenreList(ListView):
    model = models.Genre

class PublisherDetails(DetailView):
    model = models.Publisher

class PublisherList(ListView):
    model = models.Publisher

class SeriesDetails(DetailView):
    model = models.BookSeries

class SeriesList(ListView):
    model = models.BookSeries


# def series(request, series_id):
#     series = models.BookSeries.objects.get(pk=series_id)
#     ctx = {
#         'series': series
#     }
#     return render(request, template_name='series.html', context=ctx)


# def series_list(request):
#     series_list = models.BookSeries.objects.all()
#     ctx = {
#         'series_list': series_list
#     }
#     return render(request, template_name='series_list.html', context=ctx)

src/refshelf/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% include "head.html" %}
    <title>{% block title %}My amazing site{% endblock %}</title>
  </head>
  <body>
    <div> 
      {% include "navbar.html" %} 
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mt-4 mb-5 text-center">
            <h1>{% block h1 %}Page name{% endblock %}</h1>
          </div>
          <div>
            {% block content %}{% endblock %}
          </div>          
        </div>   
      </div>
    </div>
    <footer class="footer footer-style">
      <div class="container">
        <span class="text-muted">Тестовый проект: Книжный магазин Django - 2021.</span>
      </div>
    </footer>
   <!-- Option 1: Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script> 
  </body>
</html>

src/refshelf/templates/head.html
{% load static %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}" type="text/css">

src/refshelf/templates/navbar.html
{% load pcurrency %}
<nav class="navbar navbar-expand-lg navbar-dark navbar-modif">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Книжный магазин</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" {% url 'books:books' %} ">Каталог</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Справочники
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'refshelf:authors' %}">Авторы</a></li>
              <li><a class="dropdown-item" href="{% url 'refshelf:genres' %}">Жанры</a></li>
              <li><a class="dropdown-item" href="{% url 'refshelf:publishers' %}">Издательства</a></li>
              <li><a class="dropdown-item" href="{% url 'refshelf:serieses' %}">Серии книг</a></li>
            </ul>
          </li>
        </ul>
        <div class='navbar-nav d-flex'>
          <a class="nav-link" href="{% url 'carts:cart_detail' %}"><i class="bi bi-cart"></i></i>Корзина</a>
        </div>    
        <div class=" navbar-nav d-flex">
          {% if user.is_authenticated %}
            {% if user.profile.sale_staff %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Сотрудник
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href=" {% url 'users:profile' %} ">Профиль</a></li>
                    <li><a class="dropdown-item" href="{% url 'stmanager:create_res' %}">Управление</a></li>
                  </ul>
                </li>            
            {% else %}
            <a class="nav-link" href=" {% url 'users:profile' %} ">Профиль</a>
            {% endif %}
            <a class="nav-link" href=" {% url 'users:logout' %} ">Выход</a>
          {% else %}
          <a class="nav-link" href=" {% url 'users:register' %} ">Регистрация</a>
          <a class="nav-link" href=" {% url 'users:login' %} ">Вход</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  <div class='container-fluid my-1'>
  <div class='row'>
    <div class="col-md-3">
        <div class="currency_rate">
            USD:BYN {% currency_rate %}
        </div>
        
    </div>
    <div class="col-md-6">
      <form action="{% url 'books:books' %}" class="d-flex">
        <input class="form-control me-2 w-200" type="search" placeholder="Название книги или автор... " aria-label="Поиск" name="bsearch">
        <button class="btn btn-outline-secondary" type="submit" >Поиск</button>
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>